spring:
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: logiflow-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:mysql://localhost:3306/logiflow_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name:logiflow}
  prometheus:
    metrics:
      export:
        enabled: true
